[package]
name = "tls-test"
version = "0.1.0"
authors = ["Paul Sajna <sajattack@gmail.com>"]
edition = "2018"

[dependencies]
psp = { path = "../../psp" }
drogue-tls = { version = "0.2", default-features=false }
drogue-network = "0.2"
rand = { version = "0.7", default-features=false }
rand_chacha = { version = "0.3", default-features=false }

[profile.release]
lto = true

